scalar Date

type Message {
  _id: ID!
  author: String!
  room: String!
  text: String!
  created_at: Date!
}

input MessagesInput {
  author: String!
  room: String!
  text: String!
}

type Query {
  messages: [Message!]!
  messagesByRoom(room: String!): [Message!]!
}

type Mutation {
  createMessage(data: MessagesInput!): Message!
}
